export const fetchObjects = [
  {
    name: 'Licensed Steel Salad',
    description:
      'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    rating: 0,
    image: 'https://picsum.photos/500/500',
    promo: true,
    active: false,
    id: '00969c48-cb18-4486-91d9-80f739a2462d',
  },
  {
    name: 'Awesome Cotton Pizza',
    description:
      'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    rating: 2,
    image: 'https://picsum.photos/500/500',
    promo: false,
    active: false,
    id: '0119f8cb-c6e6-4c6e-ac48-5d834431a755',
  },
  {
    name: 'Tasty Soft Sausages',
    description:
      'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    rating: 1,
    image: 'https://picsum.photos/500/500',
    promo: true,
    active: false,
    id: '06d10dd7-3ac7-4898-b75e-4af86eee9df2',
  },
  {
    name: 'Practical Granite Keyboard',
    description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    rating: 3,
    image: 'https://picsum.photos/500/500',
    promo: false,
    active: true,
    id: '0abec6a2-7eeb-40f3-a63c-46e171322e06',
  },
  {
    name: 'Handcrafted Rubber Bike',
    description: 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    rating: 0,
    image: 'https://picsum.photos/500/500',
    promo: true,
    active: false,
    id: '0bb51558-b8ab-41ad-99a7-e35dffb94907',
  },
  {
    name: 'Tasty Concrete Keyboard',
    description:
      'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    rating: 4,
    image: 'https://picsum.photos/500/500',
    promo: false,
    active: true,
    id: '0de6f2b5-91b4-4b8d-b9aa-da227236d140',
  },
  {
    name: 'Unbranded Metal Shoes',
    description: 'The Football Is Good For Training And Recreational Purposes',
    rating: 5,
    image: 'https://picsum.photos/500/500',
    promo: false,
    active: false,
    id: '0edb9b17-3e97-4912-af5c-885064c7ac0e',
  },
  {
    name: 'Handmade Frozen Salad',
    description:
      'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    rating: 3,
    image: 'https://picsum.photos/500/500',
    promo: true,
    active: true,
    id: '182d607f-4243-4389-8dc0-e56116b7c399',
  },
  {
    name: 'Intelligent Concrete Chicken',
    description: 'The Football Is Good For Training And Recreational Purposes',
    rating: 3,
    image: 'https://picsum.photos/500/500',
    promo: true,
    active: false,
    id: '195289ce-c064-4faa-84c2-05a4e6dac269',
  },
  {
    name: 'Practical Rubber Car',
    description: 'The Football Is Good For Training And Recreational Purposes',
    rating: 4,
    image: 'https://picsum.photos/500/500',
    promo: false,
    active: true,
    id: '2880d095-5e52-4c6f-813f-b2bb789e95d9',
  },
];
